# A sample Gemfile
source "https://rubygems.org"

gem "activerecord", require: "active_record"
gem "sinatra"
gem "sinatra-contrib", require: "sinatra/reloader"
gem "pry"
gem "twitter"
gem "httparty"
gem "json"
gem "pg"
# gem "rails"
